site_name: GEOGLOWS Training
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode


    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


nav:
  - Home: index.md
  - Overview: overview copy.md
  - River Forecast System:
      - Part 1 Available Data:
          - GIS Data: rfs/available_data/GIS-data.md
          - Retrospective Data: rfs/available_data/retrospective.md
          - Forecast Data: rfs/available_data/forecast.md
      - Part 2 Accessing Data:
          - The Data Catalog: rfs/accessing_data/data-catalog.md
          - The Data Service: rfs/accessing_data/data-service.md
          - A Web Application: rfs/accessing_data/web-app.md
          - The Web Map: rfs/accessing_data/web_map.md
      - Part 3 Skills and Examples:
          - Accessing and Interpreting Data: rfs/skills_examples/exercises.md
          - Bias Correction and SABER Overview: rfs/skills_examples/bias-correction.md
          - Bias Correction for Forecast Data: rfs/skills_examples/forecasted-bias-correction.md
  - Publications: publications.md



