site_name: GEOGLOWS Training
nav:
  - Home: index.md
  - Overview: overview.md
  - Accessing Data: accessing-data.md
  - Retrospective Data and Validation: retrospective.md
  - Forecast Data: forecast.md
  - Applications: applications.md
