site_name: GEOGLOWS Training
nav:
  - Home: index.md
  - Overview: overview.md
  - Accessing Data: accessing-data.md
  - Retrospective: retrospective.md
  - Forecast: forecast.md
  - Applications: applications.md
