site_name: GEOGLOWS Training
nav:
  - Home: index.md
  - Accessing Data:
    - Bulk Download (AWS): data-aws.md
    - Programmatic Access: data-sources.md
    - Global Hydroviewer: hydroviewer.md
  - Retrospective Data and Validation:
    - Derivation: deriv.md
    - Return Periods & Daily Data: return.md
    - Historical Validation: historical_validation.md
    - Bias Correction: bias_correct.md
    - SABER: saber.md
  - Forecast Data:
    - Ensembles: ensemble.md
    - Statistics: stats.md
    - Initialization: initial.md
    - Bias Correction from Historical Data: bias_correct_hist.md
    - Validation: forecast_validation.md
  - Social Impact:
    - Overview: social-impact.md
    - Use Cases: use-cases.md
    - Impact Cycle: impact-cycle.md

  - Applications:
      - Flood Warning: flood-warning.md
      - Irrigation Design: irrigation-design.md
      - Reservoir Operations: reservoir-operations.md
      - GRACE Groundwater: grace-groundwater.md
      - Groundwater Mapper: groundwater-mapper.md
      - HydroServer and WMO WHOS: hydroservers.md
