site_name: GEOGLOWS Training
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Español
          build: true
          nav_translations:
            Home: "Inicio"
            Overview: "Visión general"
            River Forecast System: "River Forecast System"
            Part 1 Available Data: "Parte 1: Datos Disponibles"
            Data Catalog: "Catálogo de Datos"
            Hydrography: "Hidrografía"
            Retrospective Data: "Datos Retrospectivos"
            Forecast Data: "Datos Pronosticados"
            Part 2 Accessing Data: "Parte 2: Acceso a los Datos"
            Finding River Numbers: "Encontrar Números de Río"
            Querying Data: "Consultando Datos"
            Bulk Downloads: "Descargas Masivas"
            API (Data Service): "API (Servicio de Datos)"
            Web Maps: "Mapas Web"
            Part 3 Application Tutorials: "Parte 3: Tutoriales de Aplicación"
            Web App: "Aplicación Web"
            Understanding RFS Data: "Entendiendo los Datos RFS"
            Cookbook: "Recetario"
            Part 4 Bias Correction: "Parte 4: Corrección de Sesgo"
            SABER Method: "Método SABER"
            Correcting Forecasts: "Corregir Pronósticos"
            Publications: "Publicaciones" 
theme:
  features:
    - content.code.copy
    - content.code.select
#    - navigation.expand
    - navigation.path
    - navigation.footer
    - toc.follow
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - Home: index.md
  - Overview: overview.md
  - River Forecast System:
      - Part 1 Available Data:
          - Data Catalog: rfs/datasets/catalog.md
          - Hydrography: rfs/datasets/hydrography.md
          - Retrospective Data: rfs/datasets/retrospective.md
          - Forecast Data: rfs/datasets/forecast.md
      - Part 2 Accessing Data:
          - Finding River Numbers: rfs/accessing-data/find-river-numbers.md
          - Querying Data: rfs/accessing-data/query-data.md
          - Bulk Downloads: rfs/accessing-data/bulk-download.md
          - API (Data Service): rfs/accessing-data/data-service.md
          - Web Maps: rfs/accessing-data/web-map.md
      - Part 3 Application Tutorials:
          - Web App: rfs/tutorials/web-app.md
          - Understanding RFS Data: rfs/tutorials/exercises.md
          - Cookbook: rfs/tutorials/code-snippets.md
      - Part 4 Bias Correction:
          - SABER Method: rfs/bias-correction/bias-correction.md
          - Correcting Forecasts: rfs/bias-correction/forecasted-bias-correction.md
      - Publications: rfs/publications.md

